-- Simula bancos criados antes da migration v4, em que curtidas/salvos
-- já existiam com brecho_id do tipo uuid (caso real encontrado no Supabase).
create table if not exists public.curtidas (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  brecho_id uuid not null,
  created_at timestamptz not null default now(),
  unique (user_id, brecho_id)
);
create table if not exists public.salvos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  brecho_id uuid not null,
  created_at timestamptz not null default now(),
  unique (user_id, brecho_id)
);
