-- ============================================================
-- REPETECO — integração do banco
-- Rode no SQL Editor do Supabase ANTES de testar o projeto.
-- ============================================================

create extension if not exists pgcrypto;

-- ----------------------------
-- PROFILES
-- ----------------------------
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nome text,
  role text not null default 'usuario',
  created_at timestamptz not null default now()
);

alter table public.profiles add column if not exists nome text;
alter table public.profiles add column if not exists role text not null default 'usuario';
alter table public.profiles add column if not exists created_at timestamptz not null default now();

-- ----------------------------
-- BRECHOS
-- ----------------------------
create table if not exists public.brechos (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  nome text not null,
  descricao text,
  cidade text,
  bairro text,
  endereco text,
  categorias jsonb not null default '[]'::jsonb,
  status text not null default 'pending',
  nome_responsavel text,
  email_responsavel text,
  whatsapp text,
  instagram text,
  foto_capa text,
  criado_em timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.brechos add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.brechos add column if not exists nome text;
alter table public.brechos add column if not exists descricao text;
alter table public.brechos add column if not exists cidade text;
alter table public.brechos add column if not exists bairro text;
alter table public.brechos add column if not exists endereco text;
alter table public.brechos add column if not exists categorias jsonb not null default '[]'::jsonb;
alter table public.brechos add column if not exists status text not null default 'pending';
alter table public.brechos add column if not exists nome_responsavel text;
alter table public.brechos add column if not exists email_responsavel text;
alter table public.brechos add column if not exists whatsapp text;
alter table public.brechos add column if not exists instagram text;
alter table public.brechos add column if not exists foto_capa text;
alter table public.brechos add column if not exists criado_em timestamptz not null default now();
alter table public.brechos add column if not exists created_at timestamptz not null default now();

-- Compatibilidade com instalações que já usavam dono_id.
alter table public.brechos add column if not exists dono_id uuid references auth.users(id) on delete set null;

update public.brechos
set user_id = coalesce(user_id, dono_id)
where user_id is null and dono_id is not null;

-- ----------------------------
-- CURTIDAS
-- ----------------------------
create table if not exists public.curtidas (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  brecho_id text not null,
  created_at timestamptz not null default now(),
  unique(user_id, brecho_id)
);

alter table public.curtidas add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.curtidas add column if not exists brecho_id text;

-- ----------------------------
-- SALVOS
-- ----------------------------
create table if not exists public.salvos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  brecho_id text not null,
  created_at timestamptz not null default now(),
  unique(user_id, brecho_id)
);

alter table public.salvos add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table public.salvos add column if not exists brecho_id text;

-- ----------------------------
-- PERFIL AUTOMÁTICO NO CADASTRO
-- ----------------------------
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, nome, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'nome', new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    'usuario'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- ----------------------------
-- FUNÇÕES DE PERMISSÃO
-- ----------------------------
create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

create or replace function public.is_owner_of_brecho(p_brecho_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.brechos
    where id = p_brecho_id
      and (user_id = auth.uid() or dono_id = auth.uid())
  );
$$;

-- ----------------------------
-- RLS
-- ----------------------------
alter table public.profiles enable row level security;
alter table public.brechos enable row level security;
alter table public.curtidas enable row level security;
alter table public.salvos enable row level security;

-- Profiles: cada pessoa lê o próprio perfil; admin lê todos.
drop policy if exists "profiles_select_own_or_admin" on public.profiles;
create policy "profiles_select_own_or_admin"
on public.profiles for select
using (id = auth.uid() or public.is_admin());

drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own"
on public.profiles for insert
with check (id = auth.uid());

drop policy if exists "profiles_update_own_or_admin" on public.profiles;
create policy "profiles_update_own_or_admin"
on public.profiles for update
using (id = auth.uid() or public.is_admin())
with check (id = auth.uid() or public.is_admin());

-- Brechós: público vê somente aprovados; usuário cria o próprio; dono edita o próprio; admin gerencia tudo.
drop policy if exists "brechos_public_read_approved" on public.brechos;
create policy "brechos_public_read_approved"
on public.brechos for select
using (status in ('approved','aprovado','aprovada') or user_id = auth.uid() or dono_id = auth.uid() or public.is_admin());

drop policy if exists "brechos_insert_own" on public.brechos;
create policy "brechos_insert_own"
on public.brechos for insert
with check (user_id = auth.uid());

drop policy if exists "brechos_update_owner_or_admin" on public.brechos;
create policy "brechos_update_owner_or_admin"
on public.brechos for update
using (user_id = auth.uid() or dono_id = auth.uid() or public.is_admin())
with check (user_id = auth.uid() or dono_id = auth.uid() or public.is_admin());

drop policy if exists "brechos_delete_owner_or_admin" on public.brechos;
create policy "brechos_delete_owner_or_admin"
on public.brechos for delete
using (user_id = auth.uid() or dono_id = auth.uid() or public.is_admin());

-- Curtidas
 drop policy if exists "curtidas_select_own" on public.curtidas;
create policy "curtidas_select_own"
on public.curtidas for select using (user_id = auth.uid());

drop policy if exists "curtidas_insert_own" on public.curtidas;
create policy "curtidas_insert_own"
on public.curtidas for insert with check (user_id = auth.uid());

drop policy if exists "curtidas_delete_own" on public.curtidas;
create policy "curtidas_delete_own"
on public.curtidas for delete using (user_id = auth.uid());

-- Salvos
 drop policy if exists "salvos_select_own" on public.salvos;
create policy "salvos_select_own"
on public.salvos for select using (user_id = auth.uid());

drop policy if exists "salvos_insert_own" on public.salvos;
create policy "salvos_insert_own"
on public.salvos for insert with check (user_id = auth.uid());

drop policy if exists "salvos_delete_own" on public.salvos;
create policy "salvos_delete_own"
on public.salvos for delete using (user_id = auth.uid());

-- Índices
create index if not exists idx_brechos_status on public.brechos(status);
create index if not exists idx_brechos_user_id on public.brechos(user_id);
create index if not exists idx_curtidas_user_id on public.curtidas(user_id);
create index if not exists idx_salvos_user_id on public.salvos(user_id);

-- ============================================================
-- ANALYTICS DO BRECHÓ
-- Registra interações públicas para o painel do proprietário.
-- ============================================================
create table if not exists public.brecho_eventos (
  id bigint generated by default as identity primary key,
  brecho_id uuid not null references public.brechos(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  tipo text not null,
  created_at timestamptz not null default now()
);

alter table public.brecho_eventos enable row level security;

-- Visitantes podem registrar apenas eventos simples; se estiverem logados,
-- o user_id enviado precisa corresponder ao usuário autenticado.
drop policy if exists "eventos_public_insert" on public.brecho_eventos;
create policy "eventos_public_insert"
on public.brecho_eventos for insert
with check (user_id is null or user_id = auth.uid());

-- O dono só enxerga os eventos do próprio brechó; admin enxerga todos.
drop policy if exists "eventos_owner_select" on public.brecho_eventos;
create policy "eventos_owner_select"
on public.brecho_eventos for select
using (
  public.is_admin()
  or exists (
    select 1 from public.brechos b
    where b.id = brecho_eventos.brecho_id
      and (b.user_id = auth.uid() or b.dono_id = auth.uid())
  )
);

create index if not exists idx_brecho_eventos_brecho_id on public.brecho_eventos(brecho_id);
create index if not exists idx_brecho_eventos_tipo on public.brecho_eventos(tipo);
create index if not exists idx_brecho_eventos_created_at on public.brecho_eventos(created_at);

-- ============================================================
-- V4 — PERFIL DO CLIENTE + LOCALIZAÇÃO GOOGLE MAPS
-- ============================================================
alter table public.profiles add column if not exists cidade text;
alter table public.profiles add column if not exists bio text;
alter table public.profiles add column if not exists avatar_url text;

alter table public.brechos add column if not exists latitude double precision;
alter table public.brechos add column if not exists longitude double precision;
alter table public.brechos add column if not exists google_place_id text;
alter table public.brechos add column if not exists endereco_formatado text;

create index if not exists idx_brechos_lat_lng on public.brechos(latitude, longitude);

-- Mantém o cliente livre para editar apenas seu próprio perfil.
drop policy if exists "profiles_update_own_or_admin" on public.profiles;
create policy "profiles_update_own_or_admin"
on public.profiles for update
using (id = auth.uid() or public.is_admin())
with check (id = auth.uid() or public.is_admin());
