/* =====================================================
   REPETECO — Dashboard profissional
   Admin + dono de brechó + analytics reais
   ===================================================== */
let usuario=null, perfil=null, brechoDono=null, todosOsBrechos=[], eventosDono=[];
let filtroAprovacao='pending', brechoSelecionado=null;
const sb=()=>window.supabaseClient;
const $=id=>document.getElementById(id);
function esc(v){return String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;')}
function toast(msg){const e=$('toast');if(!e)return;e.textContent=msg;e.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>e.classList.remove('show'),2800)}
function mostrarErro(msg){const e=$('mensagemErro');if(e){e.textContent=msg;e.style.display='block'}}
function esconderErro(){const e=$('mensagemErro');if(e){e.textContent='';e.style.display='none'}}
function status(s){const x=String(s||'pending').toLowerCase();if(['approved','aprovado','aprovada'].includes(x))return{v:'approved',t:'aprovado',c:'approved'};if(['rejected','rejeitado','recusado','recusada'].includes(x))return{v:'rejected',t:'recusado',c:'rejected'};return{v:'pending',t:'pendente',c:'pending'}}
function fmtDate(v){if(!v)return'—';return new Date(v).toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit',year:'numeric'})}
function relative(v){if(!v)return'';const d=Math.max(0,Math.round((Date.now()-new Date(v).getTime())/86400000));return d===0?'hoje':d===1?'há 1 dia':`há ${d} dias`}
function initials(v){return String(v||'R').trim().charAt(0).toUpperCase()}
function voltarRepeteco(){window.location.href='../index.html'}
async function logout(){if(sb())await sb().auth.signOut();window.location.href='../index.html'}

function mostrarSecao(secao,botao){document.querySelectorAll('.nav-item').forEach(b=>b.classList.remove('active'));botao?.classList.add('active');document.querySelectorAll('.view-section').forEach(v=>v.style.display='none');const map={inicio:perfil?.role==='admin'?'adminView':'ownerView',aprovacao:'aprovacaoView',brechos:'brechosView',insights:'insightsView',perfil:'perfilView'};const target=$(map[secao]);if(target)target.style.display='block';if(secao==='inicio')perfil?.role==='admin'?carregarAdmin():carregarDono();if(secao==='aprovacao')renderAprovacaoCompleta();if(secao==='brechos')carregarTodosBrechos();if(secao==='insights')renderInsights();if(secao==='perfil')renderEditor()}
function setRoleUI(){const admin=perfil?.role==='admin';document.querySelectorAll('.admin-only').forEach(e=>e.style.display=admin?'flex':'none');document.querySelectorAll('.owner-only').forEach(e=>e.style.display=!admin?'flex':'none');$('brandContext').textContent=admin?'admin':'meu brechó';$('accountRole').textContent=admin?'administrador':'dono de brechó';$('roleChip').textContent=admin?'admin':'dono';$('accountName').textContent=perfil?.nome||usuario?.email?.split('@')[0]||'usuário';$('accountAvatar').textContent=initials(perfil?.nome||usuario?.email);}
function atualizarCabecalho(){const nome=perfil?.nome||usuario?.email?.split('@')[0]||'usuário';$('tipoPainel').textContent=perfil?.role==='admin'?'painel administrativo':'painel do brechó';$('saudacao').textContent=perfil?.role==='admin'?`Olá, ${nome}! 👋`:`Olá, ${nome}! 👋`;$('subtitulo').textContent=perfil?.role==='admin'?'acompanhe o que acontece na plataforma e revise novos espaços.':'acompanhe o desempenho do seu espaço e mantenha seu perfil atualizado.';$('usuarioEmail').textContent=usuario?.email||''}

async function iniciarDashboard(){try{if(!sb())throw new Error('Supabase não foi carregado.');const {data,error}=await sb().auth.getUser();if(error||!data?.user)return voltarRepeteco();usuario=data.user;const p=await sb().from('profiles').select('id,nome,role').eq('id',usuario.id).maybeSingle();if(p.error)throw p.error;

    // Um brechó aprovado vinculado ao usuário também determina o acesso
    // ao painel do proprietário. Isso mantém o fluxo funcionando mesmo
    // se a role do profile ainda estiver como "usuario".
    let perfilBanco=p.data||{id:usuario.id,nome:usuario.user_metadata?.nome||usuario.email?.split('@')[0]||'usuário',role:'usuario'};
    if(perfilBanco.role!=='admin'&&perfilBanco.role!=='dono'){
      const dono=await sb().from('brechos').select('*').eq('user_id',usuario.id).eq('status','approved').order('created_at',{ascending:false}).limit(1);
      if(dono.error)throw dono.error;
      if(dono.data?.length){perfilBanco={...perfilBanco,role:'dono'};}
    }
    if(!['admin','dono'].includes(perfilBanco.role))return voltarRepeteco();
    perfil=perfilBanco;setRoleUI();atualizarCabecalho();$('genericLoading').style.display='none';if(perfil.role==='admin')await carregarAdmin();else await carregarDono()}catch(e){console.error(e);$('genericLoading').style.display='none';mostrarErro('não foi possível carregar o painel. '+(e.message||''))}}

async function carregarAdmin(){esconderErro();$('adminView').style.display='block';$('aprovacaoView').style.display='none';$('brechosView').style.display='none';$('ownerView').style.display='none';$('insightsView').style.display='none';$('perfilView').style.display='none';const {data,error}=await sb().from('brechos').select('*').order('created_at',{ascending:false});if(error)throw error;todosOsBrechos=data||[];const pend=todosOsBrechos.filter(b=>status(b.status).v==='pending');const aprov=todosOsBrechos.filter(b=>status(b.status).v==='approved');const week=Date.now()-7*86400000;const novos=todosOsBrechos.filter(b=>new Date(b.created_at||b.criado_em).getTime()>=week).length;$('totalBrechos').textContent=aprov.length;$('pendentes').textContent=pend.length;$('novosSemana').textContent=novos;$('navPendingBadge').textContent=pend.length;const p=await sb().from('profiles').select('id',{count:'exact',head:true});$('totalUsuarios').textContent=p.count??'—';renderFila(pend.slice(0,5));renderAdminRecentes(aprov.slice(0,6));renderAprovacaoCompleta()}
function renderFila(items){const e=$('filaAprovacao');if(!items.length){e.innerHTML='<div class="empty">nenhuma solicitação pendente. ✨</div>';return}e.innerHTML=items.map(row).join('')}
function renderAdminRecentes(items){const e=$('ultimosBrechos');if(!items.length){e.innerHTML='<div class="empty">nenhum brechó aprovado ainda.</div>';return}e.innerHTML=items.map(b=>`<div class="compact-item"><div><strong>${esc(b.nome||'sem nome')}</strong><small>${esc([b.bairro,b.cidade].filter(Boolean).join(' · ')||'localização não informada')}</small></div><span class="compact-status">ativa</span></div>`).join('')}
function row(b){const s=status(b.status), selected=String(b.id)===String(brechoSelecionado?.id);const img=b.foto_capa?`<img src="${esc(b.foto_capa)}" alt="">`:initials(b.nome);return `<div class="approval-row ${selected?'selected':''}" onclick="selecionarBrecho('${esc(b.id)}')"><div class="row-avatar">${img}</div><div class="row-main"><strong>${esc(b.nome||'brechó sem nome')}</strong><small>${esc([b.bairro,b.cidade].filter(Boolean).join(' · ')||'localização não informada')} · ${relative(b.created_at||b.criado_em)}</small><div class="row-meta"><span class="tag">${esc(Array.isArray(b.categorias)&&b.categorias[0]?b.categorias[0]:'brechó')}</span><span class="status ${s.c}">${s.t}</span></div></div><div class="row-actions">${s.v==='pending'&&perfil?.role==='admin'?`<button class="action approve" onclick="event.stopPropagation();aprovarBrecho('${esc(b.id)}')">aprovar</button><button class="action reject" onclick="event.stopPropagation();recusarBrecho('${esc(b.id)}')">recusar</button>`:`<button class="action view" onclick="event.stopPropagation();selecionarBrecho('${esc(b.id)}')">ver</button>`}</div></div>`}
function filtrarAprovacao(f){filtroAprovacao=f;renderAprovacaoCompleta()}
function renderAprovacaoCompleta(){const e=$('approvalFullList');if(!e)return;let arr=todosOsBrechos||[];if(filtroAprovacao!=='all')arr=arr.filter(b=>status(b.status).v===filtroAprovacao);$('approvalCountLabel').textContent=`${arr.length} ${filtroAprovacao==='pending'?'pendências':'solicitações'}`;e.innerHTML=arr.length?arr.map(row).join(''):'<div class="empty">nenhum cadastro encontrado.</div>'}
async function selecionarBrecho(id){brechoSelecionado=todosOsBrechos.find(b=>String(b.id)===String(id))||null;if(!brechoSelecionado)return;renderAprovacaoCompleta();renderDetalhe()}
function renderDetalhe(){const b=brechoSelecionado;if(!b)return;const s=status(b.status);const img=b.foto_capa?`<img src="${esc(b.foto_capa)}" alt="${esc(b.nome)}">`:`<span>${initials(b.nome)}</span>`;$('adminDetail').innerHTML=`<div class="detail-cover">${img}</div><div class="detail-title"><div><h3>${esc(b.nome||'sem nome')}</h3><div class="detail-location">📍 ${esc([b.bairro,b.cidade].filter(Boolean).join(' · ')||'não informado')}</div></div><span class="status ${s.c}">${s.t}</span></div><div class="detail-block"><label>descrição</label><p>${esc(b.descricao||'Nenhuma descrição informada.')}</p></div><div class="detail-block detail-grid"><div class="detail-info"><small>categoria</small><strong>${esc(Array.isArray(b.categorias)?b.categorias.join(', '):'brechó')}</strong></div><div class="detail-info"><small>enviado em</small><strong>${fmtDate(b.created_at||b.criado_em)}</strong></div><div class="detail-info"><small>whatsapp</small><strong>${esc(b.whatsapp||'não informado')}</strong></div><div class="detail-info"><small>instagram</small><strong>${b.instagram?'@'+esc(b.instagram):'não informado'}</strong></div></div><div class="detail-block"><label>responsável</label><p>${esc(b.nome_responsavel||'não informado')} · ${esc(b.email_responsavel||'e-mail não informado')}</p></div>${s.v==='pending'?`<div class="detail-actions"><button class="action approve" onclick="aprovarBrecho('${esc(b.id)}')">aprovar e publicar</button><button class="action reject" onclick="recusarBrecho('${esc(b.id)}')">recusar</button></div>`:''}<p class="detail-note">Ao aprovar, o perfil responsável recebe a função de dono e a loja passa a aparecer no feed público.</p><div id="adminAnalyticsBlock" class="admin-analytics"><div class="loading">calculando indicadores…</div></div>`;carregarAnaliseAdmin(b.id)}
async function carregarAnaliseAdmin(id){const box=$('adminAnalyticsBlock');if(!box)return;const since=new Date(Date.now()-30*86400000).toISOString();const [ev,likes,saves]=await Promise.all([sb().from('brecho_eventos').select('tipo,created_at,user_id').eq('brecho_id',id).gte('created_at',since),sb().from('curtidas').select('id,user_id,created_at').eq('brecho_id',String(id)),sb().from('salvos').select('id,user_id,created_at').eq('brecho_id',String(id))]);const eventos=ev.error?[]:(ev.data||[]);const totalViews=eventos.filter(x=>x.tipo==='view').length;const mapClicks=eventos.filter(x=>x.tipo==='map_click').length;const likeCount=likes.error?0:(likes.data||[]).length;const saveCount=saves.error?0:(saves.data||[]).length;const uniqueUsers=new Set(eventos.filter(x=>x.user_id).map(x=>x.user_id)).size;const engagement=totalViews?Math.round(((mapClicks+likeCount+saveCount)/totalViews)*100):0;const days=[];for(let i=6;i>=0;i--){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i);days.push(d)}const counts=days.map(d=>eventos.filter(x=>{const a=new Date(x.created_at);return a>=d&&a<new Date(d.getTime()+86400000)&&x.tipo==='view'}).length);const max=Math.max(...counts,1);box.innerHTML=`<div class="detail-block"><label>desempenho · últimos 30 dias</label><div class="admin-analytics-grid"><div class="admin-mini-stat"><span>visitas</span><strong>${totalViews}</strong></div><div class="admin-mini-stat"><span>cliques no mapa</span><strong>${mapClicks}</strong></div><div class="admin-mini-stat"><span>curtidas</span><strong>${likeCount}</strong></div><div class="admin-mini-stat"><span>salvos</span><strong>${saveCount}</strong></div></div><div class="profile-health"><strong>${engagement}%</strong> de interação sobre as visitas · ${uniqueUsers} visitante(s) identificado(s) por sessão logada.</div><div class="admin-bar-chart">${counts.map((v,i)=>`<div class="admin-bar-wrap"><div class="admin-bar" style="height:${Math.max(3,(v/max)*100)}%" title="${v} visita(s)"></div><span class="admin-bar-label">${days[i].toLocaleDateString('pt-BR',{weekday:'short'}).replace('.','')}</span></div>`).join('')}</div><p class="admin-analytics-note">Os indicadores são calculados a partir das interações registradas no Repeteco. Dados sem login não entram na contagem de visitantes identificados.</p></div>`}

async function alterarStatusBrecho(id,novo){if(perfil?.role!=='admin')return;const {data:b,error:r}=await sb().from('brechos').select('id,user_id').eq('id',id).maybeSingle();if(r||!b)return mostrarErro('brechó não encontrado.');const up=await sb().from('brechos').update({status:novo}).eq('id',id);if(up.error)return mostrarErro('não foi possível alterar o status: '+up.error.message);if(b.user_id){const role=novo==='approved'?'dono':'usuario';const pr=await sb().from('profiles').update({role}).eq('id',b.user_id);if(pr.error)console.warn(pr.error.message)}toast(novo==='approved'?'brechó aprovado e publicado!':'solicitação recusada.');brechoSelecionado=null;await carregarAdmin()}
async function aprovarBrecho(id){await alterarStatusBrecho(id,'approved')}
async function recusarBrecho(id){await alterarStatusBrecho(id,'rejected')}
async function carregarTodosBrechos(){const e=$('todosBrechos');if(!e)return;e.innerHTML='<div class="loading">carregando...</div>';if(!todosOsBrechos.length){const r=await sb().from('brechos').select('*').order('created_at',{ascending:false});if(r.error)return e.innerHTML=`<div class="empty">${esc(r.error.message)}</div>`;todosOsBrechos=r.data||[]}filtrarTabelaBrechos()}
function filtrarTabelaBrechos(){const e=$('todosBrechos');if(!e)return;const q=($('brechoSearch')?.value||'').toLowerCase().trim();const arr=todosOsBrechos.filter(b=>[b.nome,b.bairro,b.cidade,b.status].join(' ').toLowerCase().includes(q));$('tableMeta').textContent=`${arr.length} loja${arr.length===1?'':'s'}`;e.innerHTML=`<div class="table-row head"><span>loja</span><span>localização</span><span>categoria</span><span>status</span><span></span></div>`+arr.map(b=>{const s=status(b.status);return `<div class="table-row"><div><strong>${esc(b.nome||'sem nome')}</strong><small>${esc(b.email_responsavel||'')}</small></div><span>${esc(b.bairro||'—')} · ${esc(b.cidade||'—')}</span><span>${esc(Array.isArray(b.categorias)?b.categorias[0]:'brechó')}</span><span class="status ${s.c} table-status">${s.t}</span><button class="action view" onclick="mostrarSecao('aprovacao',document.getElementById('navAprovacao'));selecionarBrecho('${esc(b.id)}')">ver</button></div>`}).join('')}

async function carregarDono(){document.querySelectorAll('.view-section').forEach(v=>v.style.display='none');$('ownerView').style.display='block';const r=await sb().from('brechos').select('*').eq('user_id',usuario.id).order('created_at',{ascending:false}).limit(1);if(r.error)throw r.error;brechoDono=r.data?.[0]||null;if(!brechoDono){const r2=await sb().from('brechos').select('*').eq('dono_id',usuario.id).order('created_at',{ascending:false}).limit(1);brechoDono=r2.data?.[0]||null}renderOwnerHeader();await carregarOwnerAnalytics();renderDono()}
function renderOwnerHeader(){const nome=brechoDono?.nome||'seu brechó';$('ownerTitle').textContent=`Olá, ${nome}.`;const s=brechoDono?status(brechoDono.status):null;let text=!brechoDono?'Você ainda não cadastrou um espaço.':s.v==='approved'?`Seu espaço está online. Mantenha as informações atualizadas para aparecer bem nas buscas.`:s.v==='pending'?`Sua solicitação está em análise. Você poderá publicar quando a equipe concluir a revisão.`:`Sua solicitação precisa de atenção. Confira as informações e fale com a equipe.`;$('ownerWelcomeText').textContent=text;const b=$('ownerStatusBanner');b.className=`status-banner ${s?.c||''}`;b.innerHTML=!brechoDono?'Ainda não há um brechó vinculado à sua conta. <strong><a href="../cadastro.html">cadastrar agora →</a></strong>':`status da loja: <strong>${s.t}</strong>${s.v==='approved'?' · sua página está visível no feed.':''}`}
function renderDono(){renderOwnerPreview();renderChecklist();renderSignals()}
async function carregarOwnerAnalytics(){if(!brechoDono){setOwnerStats(0,0,0,0);renderChart([]);return}const id=brechoDono.id;const [ev,likes,saves]=await Promise.all([sb().from('brecho_eventos').select('tipo,created_at').eq('brecho_id',id).gte('created_at',new Date(Date.now()-30*86400000).toISOString()),sb().from('curtidas').select('id,created_at').eq('brecho_id',String(id)),sb().from('salvos').select('id,created_at').eq('brecho_id',String(id))]);eventosDono=ev.error?[]:(ev.data||[]);const views=eventosDono.filter(x=>x.tipo==='view').length;const map=eventosDono.filter(x=>x.tipo==='map_click').length;setOwnerStats(views,map,likes.error?0:(likes.data||[]).length,saves.error?0:(saves.data||[]).length);renderChart(eventosDono);window.__ownerLikes=likes.error?[]:(likes.data||[]);window.__ownerSaves=saves.error?[]:(saves.data||[])}
function setOwnerStats(v,m,l,s){$('ownerViews').textContent=v;$('ownerMapClicks').textContent=m;$('ownerLikes').textContent=l;$('ownerSaves').textContent=s;$('insightViews').textContent=v;$('insightMap').textContent=m;$('insightLikes').textContent=l;$('insightSaves').textContent=s}
function renderChart(events){const e=$('ownerChart');if(!e)return;const days=[];for(let i=6;i>=0;i--){const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-i);days.push(d)}const counts=days.map(d=>events.filter(x=>{const a=new Date(x.created_at);return a>=d&&a<new Date(d.getTime()+86400000)&&x.tipo==='view'}).length);const max=Math.max(...counts,1);$('chartTotal').textContent=`${counts.reduce((a,b)=>a+b,0)} visitas`;e.innerHTML=counts.map((v,i)=>`<div class="chart-bar-wrap"><div class="chart-bar" style="height:${Math.max(4,(v/max)*100)}%" data-value="${v}"></div><span class="chart-label">${days[i].toLocaleDateString('pt-BR',{weekday:'short'}).replace('.','')}</span></div>`).join('')}
function renderInsights(){if(perfil?.role!=='dono')return;renderChart(eventosDono);setOwnerStats($('ownerViews').textContent,$('ownerMapClicks').textContent,$('ownerLikes').textContent,$('ownerSaves').textContent);}
function renderSignals(){const e=$('ownerSignals');if(!e)return;const values=[['visitas no perfil',Number($('ownerViews').textContent)||0],['curtidas',Number($('ownerLikes').textContent)||0],['salvamentos',Number($('ownerSaves').textContent)||0],['cliques no mapa',Number($('ownerMapClicks').textContent)||0]];const max=Math.max(...values.map(x=>x[1]),1);e.innerHTML=values.map(x=>`<div class="signal-row"><span>${x[0]}</span><div class="signal-track"><i style="width:${Math.max(3,(x[1]/max)*100)}%"></i></div><b>${x[1]}</b></div>`).join('')}
function renderOwnerPreview(){const e=$('ownerPreview'),p=$('livePreviewCard');if(!brechoDono){e.innerHTML='<div class="empty">cadastre seu brechó para visualizar a prévia.</div>';if(p)p.innerHTML='';return}const b=brechoDono;const img=b.foto_capa?`<img src="${esc(b.foto_capa)}" alt="${esc(b.nome)}">`:'👗';const html=`<div class="preview-card-image">${img}</div><div class="preview-card-body"><strong>${esc(b.nome||'Brechó')}</strong><small>📍 ${esc([b.bairro,b.cidade].filter(Boolean).join(' · '))}</small><span class="preview-tag">${esc(Array.isArray(b.categorias)&&b.categorias[0]?b.categorias[0]:'brechó')}</span></div>`;e.innerHTML=html;if(p)p.innerHTML=html}
function renderChecklist(){const e=$('ownerChecklist');if(!e)return;const checks=[['nome',!!brechoDono?.nome],['localização',!!(brechoDono?.bairro&&brechoDono?.cidade)],['descrição',!!brechoDono?.descricao],['contato',!!(brechoDono?.whatsapp||brechoDono?.instagram)],['foto de capa',!!brechoDono?.foto_capa]];e.innerHTML=checks.map(c=>`<div class="check-item ${c[1]?'':'missing'}"><span class="check-dot">${c[1]?'✓':'+'}</span><span>${c[0]}</span></div>`).join('')}
function renderEditor(){const empty=$('ownerProfileEmpty');const form=$('ownerProfileForm');if(!brechoDono){empty.style.display='flex';empty.innerHTML='<strong>nenhum brechó vinculado.</strong><p style="margin-top:6px">Cadastre seu espaço para editar o perfil.</p><a class="primary-button" style="margin-top:12px" href="../cadastro.html">cadastrar brechó →</a>';form.style.display='none';return}empty.style.display='none';form.style.display='grid';$('editNome').value=brechoDono.nome||'';$('editCategoria').value=Array.isArray(brechoDono.categorias)?(brechoDono.categorias[0]||''):'';$('editBairro').value=brechoDono.bairro||'';$('editCidade').value=brechoDono.cidade||'';$('editEndereco').value=brechoDono.endereco||'';$('editDescricao').value=brechoDono.descricao||'';$('editWhatsapp').value=brechoDono.whatsapp||'';$('editInstagram').value=brechoDono.instagram?`@${brechoDono.instagram.replace(/^@/,'')}`:'';$('editFoto').value=brechoDono.foto_capa||'';updateLivePreviewFromForm()}
function updateLivePreviewFromForm(){const name=$('editNome')?.value||'Seu brechó',loc=[$('editBairro')?.value,$('editCidade')?.value].filter(Boolean).join(' · '),cat=$('editCategoria')?.value||'brechó',foto=$('editFoto')?.value;const e=$('livePreviewCard');if(!e)return;e.innerHTML=`<div class="preview-card-image">${foto?`<img src="${esc(foto)}" alt="">`:'👗'}</div><div class="preview-card-body"><strong>${esc(name)}</strong><small>📍 ${esc(loc||'São Paulo')}</small><span class="preview-tag">${esc(cat)}</span></div>`}
async function salvarPerfilLoja(ev){ev.preventDefault();if(!brechoDono)return;const btn=$('saveProfileButton');btn.disabled=true;btn.textContent='salvando…';try{const cat=($('editCategoria').value||'brechó').split(',').map(x=>x.trim()).filter(Boolean);const payload={nome:$('editNome').value.trim(),categorias:cat,bairro:$('editBairro').value.trim(),cidade:$('editCidade').value.trim(),endereco:$('editEndereco').value.trim()||null,descricao:$('editDescricao').value.trim()||null,whatsapp:$('editWhatsapp').value.trim()||null,instagram:$('editInstagram').value.trim().replace(/^@/,'')||null,foto_capa:$('editFoto').value.trim()||null};if(payload.endereco&&window.REPETECO_CONFIG?.googleMapsApiKey&&window.localizarEnderecoGoogle){try{const geo=await window.localizarEnderecoGoogle(payload.endereco);payload.latitude=geo.latitude;payload.longitude=geo.longitude;payload.google_place_id=geo.google_place_id;payload.endereco_formatado=geo.endereco_formatado}catch(geoError){console.warn('[Repeteco] geocodificação:',geoError.message)}}const r=await sb().from('brechos').update(payload).eq('id',brechoDono.id).eq('user_id',usuario.id);if(r.error)throw r.error;brechoDono={...brechoDono,...payload};$('profileSaveMessage').textContent='alterações salvas ✓';toast('perfil atualizado!');renderOwnerHeader();renderDono()}catch(e){$('profileSaveMessage').textContent='não foi possível salvar';mostrarErro(e.message||'erro ao salvar')}finally{btn.disabled=false;btn.textContent='salvar alterações'}}
document.addEventListener('input',e=>{if(['editNome','editCategoria','editBairro','editCidade','editFoto'].includes(e.target.id))updateLivePreviewFromForm()})
function fecharModalDetalhe(e){if(e.target===$('detailModal'))$('detailModal').classList.remove('open')}

document.addEventListener('DOMContentLoaded',iniciarDashboard);
Object.assign(window,{voltarRepeteco,logout,mostrarSecao,aprovarBrecho,recusarBrecho,filtrarAprovacao,selecionarBrecho,filtrarTabelaBrechos,salvarPerfilLoja,fecharModalDetalhe,carregarAdmin,renderInsights,carregarAnaliseAdmin});
